### ISSUE TITLE
Move react-dom to devDependencies

### ISSUE THREAD

**Issue by mgtitimoli** [rikutiira/react-partial#2]
Hi @rikutiira,

I was about to start using your package when I noticed that it depends on **react-dom**.
I was having a look to the code and I noticed that it's only used in _dev.js_, and this file, as its name suggest, it's only used for dev, so...

Don't you mind moving **react-dom** to **devDependencies**?

Thanks!

**Comment by rikutiira** [comment]
Hey @mgtitimoli 

Sorry for the very late reply, I was on holidays and the issue stayed open for far longer than it should have, apologies for that.

I did as you suggested and moved **react-dom** to devDependencies. I also moved **react** there since it's already defined as peerDependency. This is now included in version 1.2.0.

Thanks for the suggestion!
